services:
  bookstore:
    image: python:3.10.8
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
      - ./.env
    depends_on:
      - db
    command:
      - uvicorn
      - bookstore.main:app
      - --workers=1
      - --host=0
      - --port=8000
      - --log-level=debug
      - --reload
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5431:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data:delegated
